remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-coffeescript

title: AIOTI WG Testbeds
description: Catalogue of IoT Solutions focused on IoT Testbeds

github:
  is_project_page: false

collections:
  solutions:
    output: true

sass:
  style: compact